version: '3.7'

services:

  ketcher_container:
    container_name: ketcher_container_prod
    build:
      context: ./ketcher_container
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx_container:/etc/nginx/conf.d:ro
    ports:
      - '1337:80'
    command: nginx -g daemon off;